"""update otp verification table

Revision ID: 9407c9a55616
Revises: f2021d2a19c1
Create Date: 2026-06-25 14:23:54.173181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9407c9a55616'
down_revision: Union[str, Sequence[str], None] = 'f2021d2a19c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('otp_verifications', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('otp_verifications', sa.Column('account_type', sa.String(length=50), nullable=True))
    op.add_column('otp_verifications', sa.Column('organization_name', sa.String(length=255), nullable=True))
    op.add_column('otp_verifications', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.alter_column('otp_verifications', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('otp_verifications', 'otp',
               existing_type=mysql.VARCHAR(length=6),
               nullable=False)
    op.alter_column('otp_verifications', 'purpose',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_verifications', 'purpose',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('otp_verifications', 'otp',
               existing_type=mysql.VARCHAR(length=6),
               nullable=True)
    op.alter_column('otp_verifications', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('otp_verifications', 'retry_count')
    op.drop_column('otp_verifications', 'organization_name')
    op.drop_column('otp_verifications', 'account_type')
    op.drop_column('otp_verifications', 'password_hash')
    op.drop_column('otp_verifications', 'full_name')
    # ### end Alembic commands ###
