"""fix otp datetime timezone

Revision ID: 966c3d2d77de
Revises: 9407c9a55616
Create Date: 2026-06-30 18:50:50.961183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '966c3d2d77de'
down_revision: Union[str, Sequence[str], None] = '9407c9a55616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_verifications', 'expires_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('otp_verifications', 'expires_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
